- hosts: localhost
  vars:
    source_key: "./.ssh/id_ed25519"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
    personal: "{{ lookup('env', 'HOME') }}/personal"
  pre_tasks:
    - name: Update Apt
      become: true
      apt:
        force_apt_get: true
        update_cache: true
        state: present
      tags:
        - install
        - core
  tasks:
    - import_tasks: tasks/ssh.yaml
    - import_tasks: tasks/core-setup.yaml
    - import_tasks: tasks/dotfiles.yaml
    - import_tasks: tasks/zsh-setup.yaml
    - import_tasks: tasks/productivity-tools.yaml
    - import_tasks: tasks/rust.yaml
    - import_tasks: tasks/docker.yaml
