- name: Install System Packages (build-essential, cmake, pkg-config)
  become: true
  apt:
    name: ["build-essential", "cmake"]
  when: ansible_facts['os_family'] == "Debian"
  tags:
    - install
    - core
