- name: Generic productivity
  community.general.homebrew:
    name: "{{ item }}"
    state: present
  with_items:
    - wget
    - fzf
    - lazygit
    - nvim
    - xclip
    - ripgrep
    - go
    - node
    - git
    - protobuf
    - protoc-gen-go
    - protoc-gen-go-grpc
    - mockery
  ignore_errors: yes
  tags:
    - install
    - productivity

- name: Install work related tools
  community.general.homebrew:
    name: "{{ item }}"
    state: present
  with_items:
    - kubernetes-cli
    - awscli
    - terraform
  ignore_errors: yes
  tags:
    - install
    - productivity

- name: Install gogoproto for work related
  shell: GO110MODULE=off go get github.com/gogo/protobuf/proto github.com/gogo/protobuf/protoc-gen-gogofast
  tags: 
  - install
  - productivity

